/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/c++ 13.3.0) */

module fsm_sar(clk_i, rst_i, start_i, cmp_i, result_o, dac_o, sample_o, eoc_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input start_i;
  wire start_i;
  input cmp_i;
  wire cmp_i;
  output [7:0] result_o;
  reg [7:0] result_o;
  output [7:0] dac_o;
  wire [7:0] dac_o;
  output sample_o;
  wire sample_o;
  output eoc_o;
  wire eoc_o;
  wire [7:0] _000_;
  wire [1:0] _001_;
  wire [1:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire [1:0] _019_;
  wire _020_;
  wire [1:0] _021_;
  wire _022_;
  wire [1:0] _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire enable;
  wire [7:0] mask_next;
  reg [7:0] mask_reg;
  wire [7:0] res_next;
  reg [7:0] res_reg;
  wire [1:0] state_next;
  reg [1:0] state_reg;
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[0] <= 1'h0;
    else if (!_010_) mask_reg[0] <= mask_next[0];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[1] <= 1'h0;
    else if (!_010_) mask_reg[1] <= mask_next[1];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[2] <= 1'h0;
    else if (!_010_) mask_reg[2] <= mask_next[2];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[3] <= 1'h0;
    else if (!_010_) mask_reg[3] <= mask_next[3];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[4] <= 1'h0;
    else if (!_010_) mask_reg[4] <= mask_next[4];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[5] <= 1'h0;
    else if (!_010_) mask_reg[5] <= mask_next[5];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[6] <= 1'h0;
    else if (!_010_) mask_reg[6] <= mask_next[6];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) mask_reg[7] <= 1'h0;
    else if (!_010_) mask_reg[7] <= mask_next[7];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[0] <= 1'h0;
    else if (enable) result_o[0] <= res_reg[0];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[1] <= 1'h0;
    else if (enable) result_o[1] <= res_reg[1];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[2] <= 1'h0;
    else if (enable) result_o[2] <= res_reg[2];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[3] <= 1'h0;
    else if (enable) result_o[3] <= res_reg[3];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[4] <= 1'h0;
    else if (enable) result_o[4] <= res_reg[4];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[5] <= 1'h0;
    else if (enable) result_o[5] <= res_reg[5];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[6] <= 1'h0;
    else if (enable) result_o[6] <= res_reg[6];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) result_o[7] <= 1'h0;
    else if (enable) result_o[7] <= res_reg[7];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[0] <= 1'h0;
    else if (_008_) res_reg[0] <= res_next[0];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[1] <= 1'h0;
    else if (_008_) res_reg[1] <= res_next[1];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[2] <= 1'h0;
    else if (_008_) res_reg[2] <= res_next[2];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[3] <= 1'h0;
    else if (_008_) res_reg[3] <= res_next[3];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[4] <= 1'h0;
    else if (_008_) res_reg[4] <= res_next[4];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[5] <= 1'h0;
    else if (_008_) res_reg[5] <= res_next[5];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[6] <= 1'h0;
    else if (_008_) res_reg[6] <= res_next[6];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) res_reg[7] <= 1'h0;
    else if (_008_) res_reg[7] <= res_next[7];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) state_reg[0] <= 1'h0;
    else if (_007_) state_reg[0] <= state_next[0];
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) state_reg[1] <= 1'h0;
    else if (_007_) state_reg[1] <= state_next[1];
  assign _013_ = ~state_reg[0];
  assign _014_ = ~state_reg[1];
  assign dac_o[0] = res_reg[0] | mask_reg[0];
  assign dac_o[1] = res_reg[1] | mask_reg[1];
  assign dac_o[2] = res_reg[2] | mask_reg[2];
  assign dac_o[3] = res_reg[3] | mask_reg[3];
  assign dac_o[4] = res_reg[4] | mask_reg[4];
  assign dac_o[5] = res_reg[5] | mask_reg[5];
  assign dac_o[6] = res_reg[6] | mask_reg[6];
  assign dac_o[7] = res_reg[7] | mask_reg[7];
  assign _008_ = _006_ & _005_;
  assign _006_ = cmp_i | _016_;
  assign _007_ = _004_ & _003_;
  assign _004_ = mask_reg[0] | _016_;
  assign _003_ = start_i | _015_;
  assign _010_ = _026_ | _028_;
  assign _012_ = _017_ | _045_;
  assign _011_ = _018_ | _045_;
  assign _018_ = _050_ | _026_;
  assign _009_ = _018_ | _028_;
  assign _047_ = _013_ | _014_;
  assign _016_ = state_reg[0] | _014_;
  assign _048_ = _013_ | state_reg[1];
  assign _017_ = _028_ | _050_;
  assign _019_[1] = _045_ | _026_;
  assign _020_ = _017_ | _019_[1];
  assign _022_ = _021_[0] | _021_[1];
  assign _023_[1] = _045_ | _049_;
  assign _024_ = _021_[0] | _023_[1];
  assign _025_ = _026_ | _012_;
  assign _027_ = _011_ | _028_;
  assign _029_ = _050_ | _045_;
  assign _046_ = _045_ | _009_;
  assign _015_ = state_reg[0] | state_reg[1];
  assign _028_ = ~_047_;
  assign _050_ = ~_016_;
  assign _045_ = ~_048_;
  assign _026_ = ~_015_;
  assign _002_[0] = mask_reg[0] ? 1'h1 : 1'hx;
  assign _000_[0] = cmp_i ? dac_o[0] : 1'hx;
  assign _000_[1] = cmp_i ? dac_o[1] : 1'hx;
  assign _000_[2] = cmp_i ? dac_o[2] : 1'hx;
  assign _000_[3] = cmp_i ? dac_o[3] : 1'hx;
  assign _000_[4] = cmp_i ? dac_o[4] : 1'hx;
  assign _000_[5] = cmp_i ? dac_o[5] : 1'hx;
  assign _000_[6] = cmp_i ? dac_o[6] : 1'hx;
  assign _000_[7] = cmp_i ? dac_o[7] : 1'hx;
  assign _001_[0] = start_i ? 1'h1 : 1'hx;
  assign _001_[1] = start_i ? 1'h0 : 1'hx;
  assign _021_[1] = _001_[0] & _026_;
  assign _021_[0] = _002_[0] & _050_;
  assign _049_ = _001_[1] & _026_;
  assign _030_ = _000_[0] & _050_;
  assign _031_ = _000_[1] & _050_;
  assign _032_ = _000_[2] & _050_;
  assign _033_ = _000_[3] & _050_;
  assign _034_ = _000_[4] & _050_;
  assign _035_ = _000_[5] & _050_;
  assign _036_ = _000_[6] & _050_;
  assign _037_ = _000_[7] & _050_;
  assign _038_ = mask_reg[1] & _050_;
  assign _039_ = mask_reg[2] & _050_;
  assign _040_ = mask_reg[3] & _050_;
  assign _041_ = mask_reg[4] & _050_;
  assign _042_ = mask_reg[5] & _050_;
  assign _043_ = mask_reg[6] & _050_;
  assign _044_ = mask_reg[7] & _050_;
  assign _005_ = ~_010_;
  assign state_next[0] = _020_ ? _022_ : 1'hx;
  assign state_next[1] = _020_ ? _024_ : 1'hx;
  assign eoc_o = _025_ ? _026_ : 1'hx;
  assign enable = _027_ ? _028_ : 1'hx;
  assign res_next[0] = _029_ ? _030_ : 1'hx;
  assign res_next[1] = _029_ ? _031_ : 1'hx;
  assign res_next[2] = _029_ ? _032_ : 1'hx;
  assign res_next[3] = _029_ ? _033_ : 1'hx;
  assign res_next[4] = _029_ ? _034_ : 1'hx;
  assign res_next[5] = _029_ ? _035_ : 1'hx;
  assign res_next[6] = _029_ ? _036_ : 1'hx;
  assign res_next[7] = _029_ ? _037_ : 1'hx;
  assign mask_next[0] = _029_ ? _038_ : 1'hx;
  assign mask_next[1] = _029_ ? _039_ : 1'hx;
  assign mask_next[2] = _029_ ? _040_ : 1'hx;
  assign mask_next[3] = _029_ ? _041_ : 1'hx;
  assign mask_next[4] = _029_ ? _042_ : 1'hx;
  assign mask_next[5] = _029_ ? _043_ : 1'hx;
  assign mask_next[6] = _029_ ? _044_ : 1'hx;
  assign mask_next[7] = _029_ ? _045_ : 1'hx;
  assign sample_o = _046_ ? _045_ : 1'hx;
  assign _023_[0] = _021_[0];
  assign _019_[0] = _017_;
  assign _002_[1] = _002_[0];
endmodule
